import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const clientRoot = join(__dirname, '..');

// Player-facing copy only. The bundle under public/dist is generated by the
// build and is not the place to fix a binding.
const copySources = [
  join('public', 'manifest.json'),
  join('public', 'desktop.html'),
  join('public', 'in_game.html'),
  join('src', 'dynamo_warning.ts'),
];

describe('toggle_overlay hotkey copy', () => {
  it('does not mention the retired Ctrl+Tab binding anywhere', () => {
    for (const relative of copySources) {
      const content = readFileSync(join(clientRoot, relative), 'utf8');
      expect(content).not.toMatch(/Ctrl\+Tab/i);
    }
  });

  it('registers Ctrl+Shift+D as the toggle binding in the manifest', () => {
    const manifest = JSON.parse(
      readFileSync(join(clientRoot, 'public', 'manifest.json'), 'utf8'),
    );
    expect(manifest.data.hotkeys.toggle_overlay.default).toBe('Ctrl+Shift+D');
  });

  it('advertises Ctrl+Shift+D on both player surfaces', () => {
    for (const relative of [join('public', 'desktop.html'), join('public', 'in_game.html')]) {
      expect(readFileSync(join(clientRoot, relative), 'utf8')).toMatch(/Ctrl\+Shift\+D/);
    }
  });

  it('deep-links into Overwolf hotkey settings by manifest hotkey name', () => {
    // The documented deep link is the only way to open Overwolf's own Overlay &
    // Hotkeys window focused on our binding, and its `hotkey` parameter has to
    // be the manifest hotkey name - not a display label. Renaming the binding
    // would otherwise break the link silently, since nothing else reads it.
    const source = readFileSync(join(clientRoot, 'src', 'index.ts'), 'utf8');
    const manifest = JSON.parse(
      readFileSync(join(clientRoot, 'public', 'manifest.json'), 'utf8'),
    );

    const deepLink = source.match(
      /overwolf:\/\/settings\/games-overlay\?hotkey=([a-z_]+)/,
    );
    expect(deepLink).not.toBeNull();
    expect(Object.keys(manifest.data.hotkeys)).toContain(deepLink?.[1]);
  });
});
